package com.qf.application.model;

public class Student {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student.id
     *
     * @mbggenerated Wed Jan 09 17:12:22 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student.name
     *
     * @mbggenerated Wed Jan 09 17:12:22 CST 2019
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student.password
     *
     * @mbggenerated Wed Jan 09 17:12:22 CST 2019
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student.stu_number
     *
     * @mbggenerated Wed Jan 09 17:12:22 CST 2019
     */
    private Integer stuNumber;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.id
     *
     * @return the value of t_student.id
     *
     * @mbggenerated Wed Jan 09 17:12:22 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.id
     *
     * @param id the value for t_student.id
     *
     * @mbggenerated Wed Jan 09 17:12:22 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.name
     *
     * @return the value of t_student.name
     *
     * @mbggenerated Wed Jan 09 17:12:22 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.name
     *
     * @param name the value for t_student.name
     *
     * @mbggenerated Wed Jan 09 17:12:22 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.password
     *
     * @return the value of t_student.password
     *
     * @mbggenerated Wed Jan 09 17:12:22 CST 2019
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.password
     *
     * @param password the value for t_student.password
     *
     * @mbggenerated Wed Jan 09 17:12:22 CST 2019
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.stu_number
     *
     * @return the value of t_student.stu_number
     *
     * @mbggenerated Wed Jan 09 17:12:22 CST 2019
     */
    public Integer getStuNumber() {
        return stuNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.stu_number
     *
     * @param stuNumber the value for t_student.stu_number
     *
     * @mbggenerated Wed Jan 09 17:12:22 CST 2019
     */
    public void setStuNumber(Integer stuNumber) {
        this.stuNumber = stuNumber;
    }
}